### ISSUE TITLE
Create conversation outside of Meteor method

### ISSUE THREAD

**Issue by creitz** [copleykj/socialize-messaging#22]
Hello,

I was previously using:

```
var conversation = new Conversation().save();
```
within the context of a Meteor method, but now I'd like to create a conversation outside the context of a Meteor method, specifically in a SyncedCron server job.  When I try do so, I get this error:

```
Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:252:19)
    at Object.Participant.appendSchema.userId.autoValue (packages/socialize_messaging.js:654:31)
    at Object.runAV (packages/aldeed_simple-schema.js:1282:26)
    at packages/aldeed_simple-schema.js:1383:13
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/aldeed_simple-schema.js:1382:7
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at [object Object].getAutoValues (packages/aldeed_simple-schema.js:1345:5)
```

It looks like the Participant model is using Meteor.userId(), which I guess would be expected since the documentation says that creating a conversation automatically adds the currently logged in user to the conversation.

Is there any way around this? Does the package support any way of creating a conversation without a logged in participant, and then I can manually add the first participant myself? 

Thanks for your help!

**Comment by copleykj** [comment]
Yeah, this package is designed to be able to work entirely from the client and in doing so enforces certain constraints through allow/deny, SimpleSchema, and CollectionHooks. The one in particular that you hare having an issue with is enforced through a hook and thus can be bypassed by using `collection.direct.insert()`.

Something like the following should work.
```javascript
Meteor.conversations.direct.insert(new Conversation());
```
Let me know is you need anything else.

**Comment by creitz** [comment]
Thank you!
