### ISSUE TITLE
[Question] Is there a live example of this package ?

### ISSUE THREAD

**Issue by JeromeVi** [copleykj/socialize-messaging#26]
Hi,
I'm interested to use your package but before I'd like to "play" a bit with it, is it an online demo ? Or a website that use your package and where I could test it ?

thank you for the answer

**Comment by StorytellerCZ** [comment]
If you want to play: https://github.com/StorytellerCZ/Socialize-starter
It is being used on Literary Universe: https://www.literaryuniverse.com

**Comment by JeromeVi** [comment]
@StorytellerCZ  Thank you for the repo, I haven't found the chat option in the Literary Universe website

**Comment by JeromeVi** [comment]
+ sorry after I cloned the repo and run : 
` meteor npm install --save sanitize-html babel-runtime react react-intl react-helmet react-router mantra-core sanitize-html string react-dom`

I got this error:
```
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
native: Converting circular structure to JSON
  at Object.stringify (native)
  at Object.stringify (/Users/swisscom_NG/.meteor/packages/meteor-tool/.1.4.3_2.10gdxww++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/core-js/modules/es6.symbol.js:224:23)
  at deepHash (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/util.js:27:18)
  at Object.exports.deepHash (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/util.js:42:10)
  at Cache.Cp.get (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:62:22)
  at Object.compile (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:48:23)
  at Object.Babel.compile (packages/babel-compiler.js:48:24)
  at packages/babel-compiler.js:162:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:192:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:161:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
  at Array.forEach (native)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:92:14)


While processing files with ecmascript (for target os.osx.x86_64):
native: Converting circular structure to JSON
  at Object.stringify (native)
  at Object.stringify (/Users/swisscom_NG/.meteor/packages/meteor-tool/.1.4.3_2.10gdxww++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/core-js/modules/es6.symbol.js:224:23)
  at deepHash (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/util.js:27:18)
  at Object.exports.deepHash (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/util.js:42:10)
  at Cache.Cp.get (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:62:22)
  at Object.compile (/Users/swisscom_NG/.meteor/packages/ecmascript/.0.6.3.hhklm4++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:48:23)
  at Object.Babel.compile (packages/babel-compiler.js:48:24)
  at packages/babel-compiler.js:162:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:192:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:161:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
  at Array.forEach (native)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:92:14)


Your application has errors. Waiting for file change.
Started MongoDB.
```

**Comment by StorytellerCZ** [comment]
@JeromeVi Seems like this is an issue that you are trying to install stuff for different version of node than meteor runs on. Try `meteor npm install` (no need to pass in the packages, they are already in the `package.json`).
As for LU, the messaging is under Messages when you are logged in. My username is Storyteller, so you can try to message me.

**Comment by JeromeVi** [comment]
@StorytellerCZ  perfect !
